document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("<head>");
document.writeln("    <meta charset=\'utf-8\'/>");
document.writeln("	<link rel=stylesheet type=\'text/css\' href=\'css/backtotop.css\'>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("");
document.writeln("<button class=\'js-back-to-top back-to-top\' title=\'回到頂端\'>&#65085;</button>");
document.writeln("	<script>");
document.writeln("	$(function () {");
document.writeln("	var $win = $(window);");
document.writeln("	var $backToTop = $(\'.js-back-to-top\');");
document.writeln("	$win.scroll(function () {");
document.writeln("	if ($win.scrollTop() > 100) {");
document.writeln("	$backToTop.show();");
document.writeln("	} else {");
document.writeln("	$backToTop.hide();");
document.writeln("	}");
document.writeln("	});");
document.writeln("	$backToTop.click(function () {");
document.writeln("	$(\'html, body\').animate({scrollTop: 0}, 200);");
document.writeln("	});");
document.writeln("	});");
document.writeln("	</script>");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");